"""empty message

Revision ID: 1f5c50b6fc1b
Revises: 41511444c956
Create Date: 2021-02-13 16:10:25.078979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5c50b6fc1b'
down_revision = '41511444c956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_answer_model_user_id_user_model'), 'user_model', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_model_user_id_user_model'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
