"""empty message

Revision ID: 42f7e1c260b7
Revises: 9192d9d773b3
Create Date: 2021-02-16 20:51:55.655255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f7e1c260b7'
down_revision = '9192d9d773b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_like',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_model.id'], name=op.f('fk_question_like_question_id_question_model'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], name=op.f('fk_question_like_user_id_user_model'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'question_id', name=op.f('pk_question_like'))
    )
    op.create_table('answer_like',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer_model.id'], name=op.f('fk_answer_like_answer_id_answer_model'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], name=op.f('fk_answer_like_user_id_user_model'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'answer_id', name=op.f('pk_answer_like'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_like')
    op.drop_table('question_like')
    # ### end Alembic commands ###
