"""empty message

Revision ID: 69397e86858c
Revises: b979c6bab9c0
Create Date: 2021-02-13 17:08:26.761906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69397e86858c'
down_revision = 'b979c6bab9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('question_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_model', schema=None) as batch_op:
        batch_op.drop_column('modified_date')

    with op.batch_alter_table('answer_model', schema=None) as batch_op:
        batch_op.drop_column('modified_date')

    # ### end Alembic commands ###
