"""empty message

Revision ID: 9192d9d773b3
Revises: 69397e86858c
Create Date: 2021-02-14 22:23:39.405349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9192d9d773b3'
down_revision = '69397e86858c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer_model.id'], name=op.f('fk_comment_model_answer_id_answer_model'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question_model.id'], name=op.f('fk_comment_model_question_id_question_model'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], name=op.f('fk_comment_model_user_id_user_model'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_model'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_model')
    # ### end Alembic commands ###
