"""empty message

Revision ID: f99b8b1e4f02
Revises: a63dd3065aa7
Create Date: 2021-02-13 15:43:44.860789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99b8b1e4f02'
down_revision = 'a63dd3065aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_question_model_user_id_user_model'), 'user_model', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_model_user_id_user_model'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
